# Generated by Django 6.0.7 on 2026-07-29 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
        ("recipe", "0003_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="recipe",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipe.recipe",
            ),
        ),
    ]
